<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Tool_Hazard</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <StartupObject>Tool_Hazard.Program</StartupObject>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Biohazard\PIX\Res.res" />
    <None Remove="Resources\Biohazard\encoding.xml" />
    <None Remove="Resources\Biohazard\encoding_file.xml" />
    <None Remove="Resources\Biohazard\font.png" />
    <None Remove="Resources\Biohazard\font_file.png" />
    <None Remove="Resources\Biohazard\Opcodes\re15_opcodes.json" />
    <None Remove="Resources\Biohazard\Opcodes\re1_opcodes.json" />
    <None Remove="Resources\Biohazard\Opcodes\re2_opcodes.json" />
    <None Remove="Resources\Biohazard\Opcodes\re3_opcodes.json" />
    <None Remove="Resources\POWER-ON.WAV" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\Biohazard\encoding.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Biohazard\encoding_file.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Biohazard\font.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Biohazard\font_file.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Biohazard\Opcodes\re15_opcodes.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Biohazard\Opcodes\re1_opcodes.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Biohazard\Opcodes\re2_opcodes.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Biohazard\Opcodes\re3_opcodes.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Biohazard\PIX\Res.res" />
    <EmbeddedResource Include="Resources\POWER-ON.WAV" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AFSLib" Version="1.1.2" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="NVorbis" Version="0.10.5" />
    <PackageReference Include="SevenZipExtractor" Version="1.0.19" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
